package: cloud.lazycat.app.regex-vis
version: 0.0.4
name: Regex Vis
description: "一个辅助学习、编写和验证正则的工具"
license: http://www.apache.org/licenses/
min_os_version: "1.5.0"
homepage: https://github.com/Bowen7/regex-vis
author: Bowen7
unsupported_platforms:
  - ios
  - android
  - tvos
locales:
  zh:
    description: "一个辅助学习、编写和验证正则的工具"
    name: Regex Vis
